In [2]:
import numpy as np

首先先来制造一些数据，可以看出来第一行和第二行是正相关，第一行第三行是负相关

In [3]:
samples = np.array([[1,2,3,4,5],
                    [9,21,31,39,52],
                    [9,8,7,5,4]])

In [8]:
mean = [np.mean(samples[0,:]),np.mean(samples[1,:]),np.mean(samples[2,:])]
mean = np.array(mean)
print(f"mean:{mean}")

mean:[ 3.  30.4  6.6]


求散布矩阵的公式为：
$$S = \sum_{i=0}^{n}(X_i - m)(X_i-m)^T$$

In [14]:
scatter_matrix = np.zeros((3,3))
for i in range(samples.shape[1]):
    scatter_matrix += (samples[:,i].reshape(3,1) - mean).dot((samples[:,i].reshape(3,1) - mean).T)
print(scatter_matrix)

[[3848.6 -116.4 3221.6]
 [-116.4 9847.6   90.6]
 [3221.6   90.6 2948.6]]



具体解释一下每个循环发生了什么，首先取出第一列$X_0=[1,9,9]$，然后让它们分别减去三行的平均数$m=[3,30.4,6.6]$
$$X_0-m=
 \left[
  \begin{matrix}
   1-3 & 3-30.4 & 3-6.6 \\
   9-3 & 9-30.4 & 9-6.6 \\
   9-3 & 9-30.4 & 9-6.6 
  \end{matrix} 
\right] 
$$
求得矩阵：
$$X_0-m=
 \left[
  \begin{matrix}
   -2 & -29.4 & -5.6\\
   6 & -21.4& 2.4 \\
   6 & -21.4& 2.4
  \end{matrix} 
\right] 
$$
转置：
$$(X_0-m)^T=
 \left[
  \begin{matrix}
   -2 & 6 & 6\\
   -29.4 & -21.4& -21.4\\
   -5.6 & 2.4& 2.4
  \end{matrix} 
\right] 
$$
相乘：
$$(X_0-m)(X_0-m)^T=
 \left[
  \begin{matrix}
   899.72 & 603.72 & 603.72\\
   603.72 & 499.72 & 499.72\\
   603.72 & 499.72 & 499.72
  \end{matrix} 
\right] 
$$
接下来的每一列都是如此，并将每一列求得的矩阵相加，就可以得到散步矩阵了

顺带一提，散布矩阵和协方差矩阵就差$1/(n-1)$
$$S = \sum_{i=0}^{n}(X_i - m)(X_i-m)^T$$
$$C = \frac{1}{n-1} \sum_{i=1}^{n}(X_i-m)(X_i-m)^T$$
所以求得散布矩阵后协方差矩阵也很容易求出来了